name: Android Build + Release
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install Dependencies
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 8.0.1 --quiet
          haxelib install openfl 9.2.1 --quiet
          haxelib install flixel 5.2.2 --quiet
          haxelib install flixel-addons 3.0.2 --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-tools --quiet
          haxelib install hxvlc --quiet
          haxelib install tjson --quiet
          
          # Force Git to use a non-interactive helper
          git config --global core.askpass /bin/echo
          
          # Using git:// protocol which is read-only and never asks for a password
          haxelib git linc_luajit git://github.com/jigsaw-4277821/linc_luajit --quiet
          haxelib git hxCodec git://github.com/polybiusproxy/hxCodec --quiet
          haxelib git extension-androidtools git://github.com/jigsaw-4277821/extension-androidtools --quiet
          haxelib git discord_rpc git://github.com/Aidan63/linc_discord-rpc --quiet
          
          haxelib run lime setup android
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK $ANDROID_NDK_LATEST_HOME
          haxelib run lime setup
        shell: bash

      - name: Compile APK
        # -final provides the best performance for your RedMagic's Snapdragon chip
        run: haxelib run lime build android -final
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          tag_name: "android-astra-${{ github.run_number }}"
          name: "Psych Online Android Build #${{ github.run_number }}"
          files: export/release/android/bin/app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
